name: API Row Count Logger

on:
  workflow_dispatch:

  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install pandas requests

      - name: Run Script
        run: |
          python github-action-test.py

      - name: Commit Log File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add etl_log.txt

          git diff --staged --quiet || git commit -m "Update ETL log"

          git push